### ISSUE TITLE
document proxies

### ISSUE THREAD

**Issue by joelburget** [gilbox/react-spark-scroll#5] opened 2015-08-03 06:08 UTC
It's unclear to me after five minutes of looking what a proxy is. Why do I need proxies? 

For example, `move` doesn't use a proxy but as far as I can tell does essentially the same thing as `spin`.

``` javascript
        {/* move */}
        <SparkScroll.h2
          timeline={{
            topBottom: { marginLeft: '-500px', opacity: 0 },
            centerCenter: { marginLeft: '0px', opacity: 1, ease: 'bouncePast' }
          }}>move</SparkScroll.h2>

        {/* spin */}
        <SparkProxy proxyId="rotate-proxy" />
        <SparkScroll.h2
          proxy="rotate-proxy"
          timeline={{
            topBottom: { rotate: '0deg' } ,
            topCenter: { rotate: '360deg' }
          }}>spin</SparkScroll.h2>
```

Anyway, I'm sure it's important, but it's not obvious why and I'd like to be told.

**Comment by gilbox** [comment] 2015-08-03 14:00
If you simply remove the proxy, you can see how `spin` breaks without it. (Ie, change the demo to this and re-build it):

```
        {/* spin */}
        <SparkScroll.h2
          timeline={{
            topBottom: { rotate: '0deg' } ,
            topCenter: { rotate: '360deg' }
          }}>spin</SparkScroll.h2>
```

The problem is that `topBottom` and `topCenter` are dynamically calculated keyframes in the animation timeline.
- `topBottom`: When the _top_ of the element hits the _bottom_ of the viewport
- `topCenter`: When the _top_ of the element hit's the _center_ of the viewport

As the element rotates **the _top_ of the element** is constantly changing. This causes the aforementioned keyframes to generate a timeline which results in animation that jumps around erratically. The simple solution is to use a proxy to make the timeline predictable. This works because  the proxy, when placed above the `h2`, is not effected by the angle of rotation

**Comment by gilbox** [comment] 2015-08-12 02:32
Closing this in light of PR #8

**Closed as completed by gilbox** 2015-08-12 02:32 UTC
